name: Deploy StylistBot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd chatbot-ollama
          git pull origin main
          npm install
          npm run build
          pm2 restart stylistbot || pm2 start npm --name stylistbot -- run start

